---
abstract: 'access plot.ly programmatically'
author:
  - 'Christian Walde <walde.christian@gmail.com>'
  - 'Christopher Parmer <chris@plot.ly>'
build_requires:
  Capture::Tiny: 0
  File::Spec: 0
  File::Temp: 0
  IO::Handle: 0
  IPC::Open3: 0
  Storable: 0
  Test::Fatal: 0
  Test::InDistDir: 0
  Test::More: 0
  strict: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300039, CPAN::Meta::Converter version 2.131560'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WebService-Plotly
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
  package:
    - DB
provides:
  WebService::Plotly:
    file: lib/WebService/Plotly.pm
    version: 1.132910
requires:
  JSON: 0
  LWP::UserAgent: 0
  Moo: 0
  perl: 5.006
  strictures: 0
  warnings: 0
resources:
  bugtracker: https://github.com/cparmer/plotlyperl/issues
  homepage: https://github.com/cparmer/plotlyperl
  repository: https://github.com/cparmer/plotlyperl.git
version: 1.132910
